import type { Metadata } from 'next';
import { Montserrat, Noto_Serif_Display } from 'next/font/google';
import './globals.css';

import { Toaster } from '@/components/ui/sonner';

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
});

const notoSerifDisplay = Noto_Serif_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-serif-display',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${notoSerifDisplay.variable} ${montserrat.variable} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
